export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const COMPLETE_PROFILE_SUCCESS = 'COMPLETE_PROFILE_SUCCESS'
export const COMPLETE_PROFILE_FAIL = 'COMPLETE_PROFILE_FAIL'

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const GET_ALL_PROFILES_SUCCESS = 'GET_ALL_PROFILES_SUCCESS'
export const GET_ALL_PROFILES_FAIL = 'GET_ALL_PROFILES_FAIL'
